export const LEAD_STATUSES = {
  TO_CONTACT: "Da contattare",
  CALLBACK_AGREED: "Richiamo concordato",
  NO_ANSWER: "Non risponde",
  NOT_INTERESTED: "Contattato non interessato",
  OUT_OF_BUDGET: "Fuori budget",
  INTERESTED: "Contatto interessato",
  INSTALLMENT_SALE: "Vendita a rate",
  FIRST_DEPOSIT: "Primo acconto",
  SECOND_DEPOSIT: "Secondo acconto",
  BALANCE_DUE: "Saldo",
  ONE_SHOT_SALE: "Vendita unica",
  GADGET_SENT: "Invio gadget",
  TICKETS_SENT: "Invio biglietti",
  LOST: "Persa",
  FLOW_CANCELLED: "Annulla flusso",
  SOLD: "Venduta"
} as const;

export const FLOW: Record<string, string[]> = {
  [LEAD_STATUSES.TO_CONTACT]: [
    LEAD_STATUSES.CALLBACK_AGREED,
    LEAD_STATUSES.NO_ANSWER,
    LEAD_STATUSES.NOT_INTERESTED,
    LEAD_STATUSES.OUT_OF_BUDGET,
    LEAD_STATUSES.INTERESTED
  ],
  [LEAD_STATUSES.CALLBACK_AGREED]: [LEAD_STATUSES.INTERESTED, LEAD_STATUSES.NO_ANSWER, LEAD_STATUSES.NOT_INTERESTED],
  [LEAD_STATUSES.NO_ANSWER]: [
    LEAD_STATUSES.CALLBACK_AGREED,
    LEAD_STATUSES.NOT_INTERESTED,
    LEAD_STATUSES.OUT_OF_BUDGET,
    LEAD_STATUSES.INTERESTED
  ],
  [LEAD_STATUSES.INTERESTED]: [LEAD_STATUSES.INSTALLMENT_SALE, LEAD_STATUSES.ONE_SHOT_SALE, LEAD_STATUSES.LOST],
  [LEAD_STATUSES.INSTALLMENT_SALE]: [LEAD_STATUSES.FIRST_DEPOSIT, LEAD_STATUSES.FLOW_CANCELLED],
  [LEAD_STATUSES.FIRST_DEPOSIT]: [LEAD_STATUSES.SECOND_DEPOSIT, LEAD_STATUSES.BALANCE_DUE, LEAD_STATUSES.FLOW_CANCELLED],
  [LEAD_STATUSES.SECOND_DEPOSIT]: [LEAD_STATUSES.BALANCE_DUE, LEAD_STATUSES.FLOW_CANCELLED],
  [LEAD_STATUSES.BALANCE_DUE]: [LEAD_STATUSES.SOLD, LEAD_STATUSES.FLOW_CANCELLED],
  [LEAD_STATUSES.ONE_SHOT_SALE]: [LEAD_STATUSES.BALANCE_DUE, LEAD_STATUSES.SOLD],
  [LEAD_STATUSES.SOLD]: [LEAD_STATUSES.GADGET_SENT, LEAD_STATUSES.TICKETS_SENT],
  [LEAD_STATUSES.GADGET_SENT]: [LEAD_STATUSES.TICKETS_SENT],
  [LEAD_STATUSES.TICKETS_SENT]: [],
  [LEAD_STATUSES.NOT_INTERESTED]: [],
  [LEAD_STATUSES.OUT_OF_BUDGET]: [],
  [LEAD_STATUSES.LOST]: [],
  [LEAD_STATUSES.FLOW_CANCELLED]: []
};

export function isValidTransition(fromStatus: string, toStatus: string) {
  if (!fromStatus || fromStatus === toStatus) return true;
  const allowed = FLOW[fromStatus] || [];
  return allowed.includes(toStatus);
}

export function getWorkflowView() {
  return {
    statuses: Object.values(LEAD_STATUSES),
    flow: FLOW
  };
}
